version: '3.8'
services:
  bot:
    image: lukasschachner/masterypointbot
    container_name: 'discord_bot'
    restart: always
    environment:
      BOT_TOKEN: NzAwMDY0MzAyMTk0ODg0NjM4.XpdfsA.hEUJB3XK2uMnYpHsr1vFctOw6Lk #__BOT_TOKEN__
